version: "3.6"

services:
  backend:
    image: backend:production
    container_name: backend_production
    command: ["npm", "run", "start:prod"]
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  db:
    image: postgres:13
    container_name: postgres_production
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
